version: '3.8'
services:
  app:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ticket_api_development

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_ticket:/var/lib/postgresql/data

volumes:
  postgres_ticket:
